### ISSUE TITLE
Syntax highlighting/autocomplete broken for .vue files

### ISSUE THREAD

**Issue by burkgames** [vuejs/vetur#1107]
- [ ] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:  Win 10 64
- Vetur version:0.16.1
- VS Code version:1.31.1

## Problem
1、none highlight for data/components/methods/props...
![image](https://user-images.githubusercontent.com/4887816/53077172-691f4180-352c-11e9-802f-db51b8aa7a4f.png)

2、import component from *.vue，complete  with autocomplete...
![image](https://user-images.githubusercontent.com/4887816/53077470-067a7580-352d-11e9-8d69-3238eae412b6.png)

if import component with none suffix，none autocomplete...
![image](https://user-images.githubusercontent.com/4887816/53077497-14c89180-352d-11e9-9232-94cfb1e31fc9.png)

## Reproducible Case
* update to the lates vs code
* updated to the lates vetur
* open a .vue file
* observe

**Comment by dezmou** [comment]
Same here, for example the autocomplete for javascript in .vue in <script> tag is not working, yet it work good in .js files. 

in both vscode and code-insiders

**Comment by robertracz** [comment]
Hey guys, same issue here. Somehow inside my script tag `export default {...`  in my .vue files cannot resolve the Vue alias... if I do `export default new Vue({...})` then it starts working but that's not a solution.

**Comment by octref** [comment]
The syntax highlighting is working for me. Did you install any other Vue extensions?

![image](https://user-images.githubusercontent.com/4033249/53130996-80f0c880-3520-11e9-8ebd-2c98fba10b8b.png)

For importing with .vue suffix, see [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md#vetur-cannot-recognize-my-vue-component-import-such-as-import-comp-from-comp).

**Comment by robertracz** [comment]
Hey @octref thanks for the quick response. So actually it turned out it was due to the fact that I opened my vscode in the parent directory of my SPA app :) I'm assuming some configuration files were not loaded correctly although the AutoComplete for the imports work (I already have a jsconfig in the root).

Not sure if we need to account for that in general, but I think it'd be helpful to come up with a documented workaround and/or highlight it in the FAQ. All the dotnet core apps have a solution folder that groups your projects together so I'm guessing I wasn't the only one who messed this up. This is my first vue project however I've had several React front end projects set up and never similar issues.

Let me know what you think,

Rob

**Comment by slanden** [comment]
@robertracz I have the same problem as you and others, and I also was in a parent directory (vue app in one subfolder, backend node app in another) but reopening vscode in the vue app folder did not fix the issue for me

**Comment by octref** [comment]
@robertracz That is tracked in https://github.com/vuejs/vetur/issues/815.

**Comment by kimini507** [comment]
Hi, I'm also having a similar problem in one of my .vue files

Tried to:
Open/close file
Uninstall/install vetur
Restart VSCode

![vetur bug](https://user-images.githubusercontent.com/4049419/55717971-26a6bb00-5a2d-11e9-9668-270a2552bfe0.PNG)

**Comment by octref** [comment]
@kimini507 Please open new issue with full file.
