### ISSUE TITLE
Allow analyzing Vue files in `node_modules`

### ISSUE THREAD

**Issue by ProTip** [vuejs/vetur#1127]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux
- Vetur version: 0.16.2
- VS Code version: 1.30.2

## Problem

This is more of a feature request. I'm currently working on a Vue/TypeScript project in which we are sharing an shared, _uncompiled_ "source" package between different projects. Currently Vetur appears to avoid analyzing anything in a `node_modules` path causing the imported type to fall back on the generic shim interface definition.

I have removed `node_modules` check from here in my extension locally and confirmed the imported type is resolved correctly:

https://github.com/vuejs/vetur/blob/73a0854b9eba3311951546a1e82a6832b523acbb/server/src/modes/script/serviceHost.ts#L219

I would like to have the option to include packages in `node_modules` for analysis. For TypeScript's part I simply need to add the package to the `includes` section of `tsconfig.json` and it will work. Perhaps the option to trust the TypeScript includes would suffice?

**Comment by octref** [comment]
> For TypeScript's part I simply need to add the package to the includes section of tsconfig.json and it will work.

So you are including `node_modules` in tsconfig?

> Perhaps the option to trust the TypeScript includes would suffice?

I turned off `node_modules` since this is a major source for perf issues.

If you do include `node_modules/<package>/**/*.vue`, they should show up here:

https://github.com/vuejs/vetur/blob/4f959983f9a1b93a6cd75c5813d9fb46d512dcc5/server/src/modes/script/serviceHost.ts#L82

Then you can stop ignoring these vue files selectively in the service host. Are you interested in doing a PR?
