### ISSUE TITLE
Add command to help diagnose virtual file issues

### ISSUE THREAD

**Issue by octref** [vuejs/vetur#1233]
Print sourcemap and virtual file in a new tab

**Comment by trixnz** [comment]
Is this related to the issues with `sourceMap[filename]` being invalid? I've noticed on *Windows* that `getFilePath` and `getfileFsPath` are being used interchangeably to compare filepaths as strings, rather than  doing a proper comparison, honouring the slash differences on Windows.

These seem to propagate out to the `findReferences`, `findDefinition`, and `doHover` providers. After playing around with the comparisons, I managed to get it to properly provide those helpers, but it seems the file URIs returned must also be of the `file://` schema, otherwise VSCode doesn't recognise them (maybe another Windows specific requirement?)

If this is unrelated, let me know and i'll prepare another issue 😃. Love the work on interpolation, I can see this being awesome once the cross-platform issues are ironed out!

**Comment by octref** [comment]
You are right, one of them was used to handle the Windows `\` slashes. Would love more details so I can fix this!

Meanwhile I'll try to setup an Azure DevOps CI so I can get my changes tested in Windows too.

**Comment by trixnz** [comment]
I pushed my WIP changes to https://github.com/trixnz/vetur/tree/wip-interpolation-compat, granted I didn't really know what I was doing as I'm still fairly new to the vetur codebase, but this got hover and go to definition working fine, but find all references still produces the wrong URI in the returned results, so you end up with the origin of the symbol being under the wrong path, but the template references are fine.

**Comment by octref** [comment]
@trixnz I meant this feature for this issue:

![image](https://user-images.githubusercontent.com/4033249/56695758-ac1da280-669e-11e9-913f-fd64c0fc7d98.png)

Now you can run the command "Vetur: Show corresponding virtual file and sourcemap" and Vetur will open a virtual text document with these info. Should simplify debugging a lot. @ktsn FYI

**Comment by octref** [comment]
Meanwhile I opened #1235. I'll take a look of your changes. Thanks again!
