### ISSUE TITLE
The Vue Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted

### ISSUE THREAD

**Issue by zq-suiyue** [vuejs/vetur#1239]
- [ Y] I have searched through existing issues
- [ N] I have read through [docs](https://vuejs.github.io/vetur)
- [ N] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: 
- Vetur version:0.19.1
- VS Code version:1.33.1

### I received an error from vetu,suach as title
> This is the details，please help me

![image](https://user-images.githubusercontent.com/49273447/56704151-a6779980-673e-11e9-84d9-683f5e74148d.png)

![image](https://user-images.githubusercontent.com/49273447/56704168-b68f7900-673e-11e9-8d05-e3c07463dcb3.png)

**Comment by edtam** [comment]
I got the same mistake just now.
Open "C:\Users\Administrator\.vscode\extensions\octref.vetur-0.19.1\server".
Run "npm i" in your command.

**Comment by zq-suiyue** [comment]
Thank you very much

**Comment by octref** [comment]
@zq-suiyue This is caused by VS Code not updating extensions correctly. From the screenshot you are using 0.19.0. You can try this:

- Run command: `Developer: Reinstall Extension` for Vetur.
- Remove Vetur in your [extensions folder](https://code.visualstudio.com/docs/editor/extension-gallery#_common-questions) and do a clean reinstall.
- (Windows): Try reinstall Vetur with admin permission.
- If nothing above works, download the [latest pre-packaged vsix file](https://github.com/vuejs/vetur/releases) and [install through vsix](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix).
