### ISSUE TITLE
Render method causes errors in typescript

### ISSUE THREAD

**Issue by schnetzi** [vuejs/vetur#1406]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS 10.14.6
- Vetur version: 0.22.2
- VS Code version: 1.37.1

## Problem

Renderless component method `render()` causes error in typescript. The code in general works but following errors are showing up.
![image](https://user-images.githubusercontent.com/5382986/63697830-8dc6df80-c815-11e9-916c-24ffa95db818.png)

### Console error:
![image](https://user-images.githubusercontent.com/5382986/63698055-00d05600-c816-11e9-8cf6-820fd71ba0d9.png)

## Reproducible Case

I made an example project with my problems:
https://github.com/schnetzi/vetur-problem

## What I tried so far

Commenting out the render function makes the errors disappear.

**Comment by ktsn** [comment]
As compile error message said, you are directly returning the return value of scoped slots which the type is not matched with the return type of `render` function. i.e. scoped slot can be an array of `VNode` but you cannot return an array in `render` function.

Wrap with some `<div>` or filter out the scoped slot nodes to be one node.

Also you may need to annotate the return type of `render` because of this restriction:
https://vuejs.org/v2/guide/typescript.html#Annotating-Return-Types
