### ISSUE TITLE
Why do I automatically format the js code every time I git commit the code?

### ISSUE THREAD

**Issue by hello-lun** [vuejs/vetur#1436]
Why do I automatically format the js code every time I git commit the code?
the code before i used git commit:
![image](https://user-images.githubusercontent.com/34638158/65239566-dff7d980-db11-11e9-9891-84ba68aa461c.png)

the code after i used git commit:
![image](https://user-images.githubusercontent.com/34638158/65239547-ceaecd00-db11-11e9-98c3-0b6ea1fac8a9.png)

I want the code to be the same, what should I do?

**Comment by jackkoppa** [comment]
This is very likely unrelated to Vetur; most likely, you have a commit hook enabled because of the way Vue CLI initializes projects. Check [this](https://cli.vuejs.org/guide/cli-service.html#git-hooks) out, and see if you find a similar command in your `package.json`. You can delete that block if wanted, or adjust your linting rules to get the formatting that you want.

**Comment by ktsn** [comment]
It's likely unrelated to Vetur as @jackkoppa described.
