### ISSUE TITLE
Property '$router' does not exist on type 'ConstomComponent'

### ISSUE THREAD

**Issue by tangsj** [vuejs/vetur#1455]
@Component
export default class OptionBar extends Vue {
  @Prop({ default: [] })
  private options!: [];

  @Emit()
  private optionClick(option: { name: string, label: string }) {
    return option.name;
  }

  private logout() {
    this.$router.push('/login');
  }
}

在vscode 内  this.$router 位置会提示   
·
Property '$router' does not exist on type 'OptionBar'
·

项目实际编译是没有问题的

**Comment by ktsn** [comment]
This is likely because the vue-router typing is not loaded correctly and not Vetur issue. Please make sure that this problem does not happen on normal TypeScript file and provide some reproduction if you think it is a Vetur issue.

Please open a new issue with a reproduction if you can confirm that this is surely Vetur issue. Thank you.

**Comment by anqinghang** [comment]
If there are more than one work in you "workspace", please make sure the vue project in the first.
