### ISSUE TITLE
Same code. Why one of them is wrong? TS type

### ISSUE THREAD

**Issue by hzgotb** [vuejs/vetur#1479]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.22.6
- VS Code version: 1.39.2

![image](https://user-images.githubusercontent.com/50480095/67444833-473b0900-f63d-11e9-8763-9e5e45ade639.png)
![image](https://user-images.githubusercontent.com/50480095/67444846-515d0780-f63d-11e9-9306-aa7a3a34bab9.png)

**Comment by ktsn** [comment]
This is likely because you are not specifying `Vetur: Use Workspace Dependencies` setting and caused by different TS versions between each file type.
In the latest TypeScript version, you need to always specify return type of computed property if return type need to be inferred from `this` type. See: https://github.com/vuejs/vue/issues/9873
