### ISSUE TITLE
webpack aliases doesn't work in a multi-folder workspace

### ISSUE THREAD

**Issue by Coolyang1996** [vuejs/vetur#1572]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows 10 
- Vetur version: 0.22.6
- VS Code version: 1.40.2(user setup)

## Problem
In a workspace, if the vue project folder is not first place in this workspace, webpack aliases doesn't work, so go to definition can not work.
```
// jsconfig.json
{
  "include": [
    "./src/**/*"
  ],
  "exclude": [
    "node_modules",
    "dist"
  ],
  "compilerOptions": {
    "checkJs": true,
    "baseUrl": ".",
    "paths": {
      "@/*": [
        "./client/*"
      ]
    }
  }
}

```
## Reproducible Case
1. clone [reproduction repo](https://github.com/Coolyang1996/veturpack)
2. create a empty folder
3. create a workspace A , add the reproduction, add the empty folder.
4. create a workspace B , add the empty folder, add the reproduction.

Now, open Home.vue from workspace A  , select `Counter` and go to definition works. But in  workspace B, go to definition doesn't work.

![微信图片编辑_20191130095226](https://user-images.githubusercontent.com/34713301/69894200-856fca80-1357-11ea-8415-e14ce6d4cbe1.jpg)
![微信图片编辑_20191130095328](https://user-images.githubusercontent.com/34713301/69894201-87398e00-1357-11ea-8cdf-82611170ed38.jpg)

Maybe jsconfig.json not work?

**Comment by vojvodics** [comment]
Looks like we have the same problem. 
In a workspace setup, vetur autocompletes from the first projects jsconfig.json

My setup: 
- app project
   - jsconfig.json
- ui lib
  - jsconfig.json

In ui lib in any `*.vue` file I get autocomplete like this: (which is a config from app project)
<img width="496" alt="Screen Shot 2019-12-04 at 10 17 38 AM" src="https://user-images.githubusercontent.com/20173051/70129749-a26e0b80-167f-11ea-8cb4-fdef4504d803.png">

However, this works normally for js files (presumably because because i did not configure vetur for js files so regular vscode path works for js files)
<img width="519" alt="Screen Shot 2019-12-04 at 10 18 17 AM" src="https://user-images.githubusercontent.com/20173051/70130060-2d4f0600-1680-11ea-899c-30e6e6046e0d.png">

**Comment by Coolyang1996** [comment]
> Looks like we have the same problem.
> In a workspace setup, vetur autocompletes from the first project jsconfig.json
> 
> My setup:
> 
> * app project
>   
>   * jsconfig.json
> * ui lib
>   
>   * jsconfig.json
> 
> In ui lib in any `*.vue` file I get autocomplete like this: (which is a config from app project)
> <img alt="Screen Shot 2019-12-04 at 10 17 38 AM" width="496" src="https://user-images.githubusercontent.com/20173051/70129749-a26e0b80-167f-11ea-8cb4-fdef4504d803.png">
> 
> However, this works normally for js files (presumably because because i did not configure vetur for js files so regular vscode path works for js files)
> <img alt="Screen Shot 2019-12-04 at 10 18 17 AM" width="519" src="https://user-images.githubusercontent.com/20173051/70130060-2d4f0600-1680-11ea-899c-30e6e6046e0d.png">

Yep, the js files work well.

**Comment by Coolyang1996** [comment]
BTW, the ESLint extension for VSCode has a `eslint.workingDirectories` option to solve this similar issue. 
[microsoft/vscode-eslint](https://github.com/microsoft/vscode-eslint#settings-options)

**Comment by octref** [comment]
This is the same underlying issue as https://github.com/vuejs/vetur/issues/815
