### ISSUE TITLE
Vetur typescript v-data type union not working

### ISSUE THREAD

**Issue by sultanmyrza** [vuejs/vetur#1619]
## Info

- Platform:  macOS
- Vetur version: 0.22.6
- VS Code version: 1.41.1

## Problem

https://media.giphy.com/media/JobN0giU9tE5qGzaac/giphy.gif
## Reproducible Case

create fresh vue 2 project with typescript support

**Comment by ktsn** [comment]
This is not Vetur's issue. TypeScript narrows variable type when you initialize a variable with `null`.
https://www.typescriptlang.org/play/#code/DYUwLgBGIM5gXBOAnAlgOwOYQD4XQK7DAQC8+RwAUAMYD26MdoAdMHZgBTRwCUQA

You need to cast `null` rather than annotating the variable.
https://www.typescriptlang.org/play/#code/DYUwLgBGIM6QvBAdgV2MCBDGE4CcBLJAcwgB9k1gAoAYwHskZ7QA6Ye4gCmjgEogA

**Comment by sultanmyrza** [comment]
Thank you very much @ktsn  it worked for me (Typescritp, Vetur)
let test: string | null = null // Didn't worked 
let test = null as string | null // Worked
