### ISSUE TITLE
Autocomplete not working for import with @

### ISSUE THREAD

**Issue by fractalf** [vuejs/vetur#1673]
When using the `@` alias in imports the autocomplete doesn't work

![image](https://user-images.githubusercontent.com/5707457/72970331-b7d1fd00-3dc7-11ea-86a2-5b521042066d.png)

vs

![image](https://user-images.githubusercontent.com/5707457/72970362-c5878280-3dc7-11ea-9d25-e0dc79cf700d.png)

`ACTIONS` is a const exported from the given file and is what should show up

**Comment by samtheprogram** [comment]
You'll need to set up a jsconfig (or tsconfig if you're using Typescript or a hybrid project) as described in the FAQ [here](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md#vetur-cant-recognize-components-imported-using-webpacks-alias) -- note the Webpack part is already preconfigured from the vue-cli, you just have to set up the jsconfig/tsconfig part.

Additionally, if you're importing Vue files, be sure to use the `.vue` extension in the file path, [otherwise Vetur won't support that](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md#vetur-cannot-recognize-my-vue-component-import-such-as-import-comp-from-comp).

**Comment by octref** [comment]
You are encountering #762.
