### ISSUE TITLE
Vetur does not recognize validations from Vuelidate

### ISSUE THREAD

**Issue by AllanOricil** [vuejs/vetur#1984]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

- Platform: Win
- Vetur version: 0.24.0
- VS Code version: 1.46.0

## Problem

![image](https://user-images.githubusercontent.com/55927613/84578456-bf586980-ad9b-11ea-905b-fda7288af582.png)

I can compile my code but it sucks to have this Vetur message. How can I disable it?

This is the entire error message:
```
No overload matches this call.
  The last overload gave the following error.
    Argument of type '{ created(): void; data(this: CombinedVueInstance<Vue, unknown, unknown, unknown, Readonly<Record<never, any>>>): { sObjectDefinition: { name: string; label: string; ... 14 more ...; deploymentStatus: string; }; creatingCustomObject: boolean; }; watch: { ...; }; methods: { ...; }; validations: {}; }' is not assignable to parameter of type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>>'.
      Object literal may only specify known properties, and 'validations' does not exist in type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>>'.Vetur(2769)
````

**Comment by octref** [comment]
Your issue is closed because you did not provide a repro case. Please read https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md and open a new issue.

---

https://vuejs.org/v2/guide/typescript.html

**Comment by matyasfodor** [comment]
Same issue

**Comment by emdahlstrom** [comment]
Yeah same here

**Comment by AllanOricil** [comment]
@emdahlstrom could you provide an example case like they are asking?

**Comment by emdahlstrom** [comment]
@AllanOricil I was working on an example but the problem mysteriously went away. Maybe it's one of those things that are kind of hard to debug because you need to refresh the editor. I've run into weird typescript errors before that have just been typescript bothering about old issues. 

In any case, now when I go back to my original code base the problem has disappeared there as well. :confused: 

The only thing I can remember doing in the example repo is:
> rm -rf node_modules && rm yarn.lock && yarn

Here is my example repo if you want to compare anything to yours. Or see if it works on your machine:
https://github.com/emdahlstrom/ts-nuxt-lab

**Comment by Snitovets** [comment]
Same issue. Also installed @types/vuelidate didn't made thing

**Comment by Snitovets** [comment]
removing node_modules and package-lock.json and reinstalling packages fix the problem
