### ISSUE TITLE
Fallback to VLS bundled @prettier/plugin-pug for formatting when prettier is in workspace

### ISSUE THREAD

**Issue by octref** [vuejs/vetur#2014]
- Have a workspace with prettier installed locally
- Format a vue file with pug section
- Formatting won't work. This is because prettier installed in workspace won't search the dependency folder of vls

**Comment by johndatserakis** [comment]
Hey there @octref - we're running into the same issue as well when using `<template lang="pug"></template>` blocks. I see that this issue was logged a few months back - have you run into anything since that could lead to a fix? I could look into it further if you have a few more clues available.

Like you, we have prettier installed locally.

All other formatting is working correctly in our Vue single file components - `html`, `javascript`, `scss`. Everything formats automatically without issue.

We're using:

Vetur: 0.27.3
All vue-cli packages at 4.5.0

Other relevant packages:

prettier: 1.19.1
pug: 3.0.0
pug-plain-loader: 1.0.0

Thank you.

**Comment by Shinigami92** [comment]
@johndatserakis You mention `prettier: 1.19.1` :warning: 
Please try `prettier: 2.1.1`

**Comment by johndatserakis** [comment]
@Shinigami92 thank you for the quick reply. 

In response to your post, I deleted my `yarn.lock`, `node_modules`, and upgraded `prettier` to the latest version and unfortunately it didn't work. Thanks for the suggestion though.
