### ISSUE TITLE
How to setup Vetur for linking data between template and script in .vue file?

### ISSUE THREAD

**Issue by jozefliska** [vuejs/vetur#2281]
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)

## Info

- Platform: Win 10
- Vetur version: 0.27.3
- VS Code version: 1.49.0

Please, how Can I set my Vetur plugin for linking data between template and script in .vue file? See image below:
![image](https://user-images.githubusercontent.com/16937671/93452882-3d676780-f8d9-11ea-85b5-8618f5a93e8a.png)
I need to go to row 8 (greeting data definition) after click on string greeting in row 2 (where I using it).
In my default settings it not working.
Thanks.

**Comment by chanlito** [comment]
Have you enabled template interpolation service in the Vetur settings? I see this is just plain JS object. Not sure if Vetur supports that.

**Comment by octref** [comment]
Your issue is closed because you did not provide a repro case. Please read https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md and open a new issue.

Please provide a reproducible sample:
 
![image](https://user-images.githubusercontent.com/4033249/93731400-5a64a900-fbff-11ea-8d10-dcac47c76c2a.png)
