### ISSUE TITLE
Enable the use of the new emmet feature in vscode 1.13

### ISSUE THREAD

**Issue by MWallin** [vuejs/vetur#232]
With the new emmet configured I lose the feature completley in template sections in .vue files. It would be super awesome to get this back!

Link to the new feature in the update post:
https://code.visualstudio.com/updates/v1_13#_emmet-abbreviation-expansion-in-suggestion-list

**Comment by octref** [comment]
I'm interested in doing that too.

@ramya-rao-a Wondering if I need to extract `extensions/emmet`, or will new emmet continue to support `syntaxProfiles`.
I do have vue file regions marked correctly with their embedded lang.

Previously this worked fine:

```json
  "emmet.syntaxProfiles": {
    "vue": "html",
    "vue-html": "html"
  }
```

**Comment by octref** [comment]
@ramya-rao-a NVM didn't see it on the May iteration issue, but saw on Microsoft/vscode#27697.

To all others: syntax profile seem to be on the agenda for VSCode June release.

**Comment by ramya-rao-a** [comment]
Yes, actually supporting `syntaxProfiles` was the next thing in my list of to-dos for emmet. You will see this in the next few days in the Insiders.

**Comment by octref** [comment]
If you get it before 22nd I can demo its awesomeness at VueConf 😉

**Comment by ramya-rao-a** [comment]
haha, sure I'll try

**Comment by ramya-rao-a** [comment]
@octref I just pushed in the changes required to support this. It didn't make it to Tuesday's Insiders build though. Can you test from master and see if it works as expected for you?

**Comment by octref** [comment]
👍 👍 👍 
![show](https://user-images.githubusercontent.com/4033249/27319976-5f69821e-5594-11e7-8116-4e34450afdbb.gif)

**Comment by octref** [comment]
Closing since this will be available in VSCode's June release.

**Comment by octref** [comment]
@ramya-rao-a 

I'll just report issues here instead of opening new ones at VSCode.

![image](https://user-images.githubusercontent.com/4033249/27329251-45e97eea-55b5-11e7-9f8b-fc8542fd99b9.png)

![image](https://user-images.githubusercontent.com/4033249/27329252-462f94e8-55b5-11e7-8da0-159ae82d533d.png)

**Comment by ramya-rao-a** [comment]
Logged https://github.com/Microsoft/vscode/issues/29114
Cant guarantee this one by the 22nd :)

**Comment by octref** [comment]
Reopen to keep track of integrating https://www.npmjs.com/package/vscode-emmet-helper

**Comment by octref** [comment]
@ramya-rao-a 
Took a look but the helper presumes access to `vscode` which Vetur can't include in its LS.
To make it usable by other LS, it should take types from `vscode-languageserver-types`.

**Comment by ramya-rao-a** [comment]
@octref Good point.

I am out for the week at a conference, won't have time to make the change.
If you don't mind, can you send a PR to the helper?

**Comment by ramya-rao-a** [comment]
@octref I have updated the helper.

Language servers can now call `doComplete(document, position, syntax, emmetConfig);`
where `emmetConfig` is an object following the interface. I'll add types soon

```
export interface EmmetConfiguration {
	useNewEmmet: string;
	showExpandedAbbreviation: string;
	showAbbreviationSuggestions: boolean;
	syntaxProfiles: object;
	variables: object;
}
```

Can you give it a try?

**Comment by octref** [comment]
Thanks a lot. Just landed in China from Warsaw -- I'll give it a try soon.

**Comment by ramya-rao-a** [comment]
@octref On second thoughts, it would be much better if we include this completion provider in html and css language service. That way vue and other languages that already have html/css completions using the built-in html/css extensions get it for free.

Let me know if you want to collaborate on that

**Comment by octref** [comment]
I'd want to collaborate on that. But OTOH our plan is to rewrite / extend on the html LS for supporting Vue's js-in-template like `<div v-if="this.foo > 5">`, instead of keep depending on html LS.

Believe that's the same case for ember / angular templates, so I don't know if it's worth it.

It's just China internet gives me a hard time + I'm busy traveling...I'll give it a shot tonight.

**Comment by HerringtonDarkholme** [comment]
I found this works.

```json
  "emmet.includeLanguages": {
    "vue": "html",
    "vue-html": "html"
  }
```

**Comment by CurtisLiong** [comment]
@HerringtonDarkholme It works, this setting fixed my problem, thanks!

**Comment by zhuqingguang** [comment]
since i install the vscode of 1.15, vetur does not work any more.   Before the detected language is `vue component`, now it's vue, but does not work
![animation](https://user-images.githubusercontent.com/24694223/29257815-87f32cb6-80e7-11e7-9489-41615ed48816.gif)

**Comment by chulinyin** [comment]
@zhuqingguang  you can see the solution above the comments.  just use the follow code in setting
```
"emmet.includeLanguages": {
    "vue": "html",
    "vue-html": "html"
  }
```
instead of use `emmet.syntaxProfiles`.   And you can see my  [comments](https://github.com/vuejs/vetur/issues/383) in details.

**Comment by wernerm** [comment]
In this case the documentation might need to be updated, in order to reflect the support for new Emmet, since most users will be referencing the current (outdated) documentation on [https://vuejs.github.io/vetur/emmet.html](https://vuejs.github.io/vetur/emmet.html) when they install the vetur extension in vscode.

(I realise that the current documentation is referencing this issue, but the configuration information above was not available at the time when I opened issue #383.)

**Comment by doommm** [comment]
I get confused with settings below:
`"emmet.includeLanguages": {
    "vue": "html", 
    "vue-html": "html"
  }`
I found that if i add `"vue": "html"` to the setting, emmet works in <script> tag(*.vue). Does it work conrectly?

**Comment by HerringtonDarkholme** [comment]
@doommm No, it is current limitation of emmet. Emmet does not recognize embedded languages like style and script. Currently, embedded language support needs vetur's implementation.

**Comment by octref** [comment]
@ramya-rao-a Is this https://github.com/Microsoft/vscode/issues/29758 solvable by passing in any parameters to `vscode-emmet-helper`? I have the emmet almost ready but after typing out the `div*` in `div*3`, completion list disappears.

I can manually trigger completion using `Ctrl+Space`, though.

![emmet](https://user-images.githubusercontent.com/4033249/29274671-9bf1b004-80d6-11e7-99dc-aed10d613e20.gif)

**Comment by nerdyglasses** [comment]
Thx for `Ctrl+Space`. That helps me through this rough time.

**Comment by romanrei** [comment]
for me `ctrl+space` doesn't work :(

**Comment by ramya-rao-a** [comment]
@octref Do you have wordPattern defined for vue?

I saw something similar for twig and after defining the wordPattern, the suggestions worked as expected. See https://github.com/Microsoft/vscode/issues/32438

**Comment by HerringtonDarkholme** [comment]
Hi @ramya-rao-a. We do have wordPattern defined for Vue. https://github.com/vuejs/vetur/blob/master/client/src/htmlMain.ts#L42

But we cannot rely on it because word patterns are different across script/style/template parts in Vue.  Defining one pattern to suit all parts is almost impossible.

A better approach is using wordPattern based on syntax highlight group, that is, if users typing in style tags, we take the wordPattern of CSS, not Vue. Similarly script/template can have the same behavior. 

I don't know if vscode can do this, though.

**Comment by ramya-rao-a** [comment]
Thanks @HerringtonDarkholme 

@octref I think what is missing in your case is the trigger characters. These are the trigger chars I use for html: https://github.com/Microsoft/vscode/blob/master/extensions/emmet/src/util.ts#L14

**Comment by octref** [comment]
NVM found it.
https://github.com/vuejs/vetur/blob/master/server/src/vueServerMain.ts#L54

@ramya-rao-a 
But I'm wondering what are the `!` and `}` for in your list of trigger chars for html.

**Comment by ramya-rao-a** [comment]
@octref I found that I needed `!` for the few emmet snippets that start with `!` like `!` and `!!!`.
`}` is needed for cases like `span{This is text inside the span}`

**Comment by HerringtonDarkholme** [comment]
@ramya-rao-a  
If I change this line https://github.com/Microsoft/vscode/blob/master/extensions/emmet/src/defaultCompletionProvider.ts#L22

to 

`if (syntax === 'html')`, then emmet in Vue's style part correctly provides style completion.

<img width="873" alt="screen shot 2017-08-16 at 4 48 14 pm" src="https://user-images.githubusercontent.com/2883231/29355491-d8f4aaa0-82a3-11e7-8c9e-ed70802ed81d.png">


The reason here is if one filetype's syntax is html compatible, it can also include sub part like script / style. So we can apply same logic to the filetype as html's to dynamically set completion candidate.

**Comment by ramya-rao-a** [comment]
@HerringtonDarkholme That `if` is to check if the file can be parsed using the Emmet parser.

`syntax` can be html for a `javascript` file too, in which case parsing can fail.

But I forget that I have a check for it failed parsing later on. 

Feel free to send a PR with your suggested change.

But also remember to return the syntax as is when parsing fails at https://github.com/Microsoft/vscode/blob/master/extensions/emmet/src/defaultCompletionProvider.ts#L66

**Comment by ramya-rao-a** [comment]
@octref What happens when users have mapped `vue-html` to `html` and are getting emmet suggestions out of the box?

**Comment by octref** [comment]
That works partially. `vue-html` is only for the template region, so they wouldn't have it for css/less/scss/stylus emmet

**Comment by ramya-rao-a** [comment]
I get that, I am wondering if they will get double suggestions in the `vue-html` region

**Comment by octref** [comment]
Just tested https://github.com/Microsoft/vscode/issues/22585#issuecomment-318791783, for `includeLanguages`,

- `vue-html` to `html`: no effect at all. dunno why he added this
- `vue` to `html`: works fine in template. With my new change, having this setting will have double suggestions in `template` but not in other regions

**Comment by yyx990803** [comment]
With a fresh install of everything from yesterday, the following seems to be working without double suggestions:

```
    "emmet.includeLanguages": {
        "vue": "html"
    }
```

**Comment by octref** [comment]
@yyx990803 Got u sir.

0.9.4 should work with html/css/scss/less/stylus, without `includeLanguages`.
(With your current setting there will be duplicate emmet suggestions in `<template>`.)

![hn](https://user-images.githubusercontent.com/4033249/29460154-de46c554-83f4-11e7-8cd4-809dce812af3.gif)

**Comment by yyx990803** [comment]
Just tested and it works perfectly now (without any emmet settings)! :100:

**Comment by wernerm** [comment]
It now works for me too in Vue template, **however** I can only seem to complete valid HTML5 elements - custom element names do not get completed, eg: `<my-element>` does not get completed, but `<div>` does.

**Comment by ramya-rao-a** [comment]
@wernerm That is intentional. Emmet has no way of differentiation custom element names from text that are not meant to be abbreviations. We needed to avoid suggesting every word ever typed as a tag.

So we maintain a white list for commonly used HTML5 elements (So `div`, `span` etc will trigger emmet suggestions)

Keep in mind `my-element.my-class` will expand as expected

To expand just the custom element, use `Emmet: Expand Abbreviation` command directly or via a key binding or set `emmet.triggerExpansionOnTab` to `true` to expand on tab

**Comment by wernerm** [comment]
@ramya-rao-a Thanks for the information. 

Since custom element names are quite common in Vue it would be nice if we could somehow add to the white-list of element names. (One of the main purposes of Emmet is to save keystrokes after all.)

**Comment by ramya-rao-a** [comment]
You can add it to your custom snippets. See [Custom Snippets in Emmet](https://code.visualstudio.com/docs/editor/emmet#_using-custom-emmet-snippets) on how to have custom snippets in Emmet.

In your case it would look like
```
{
    "html":
         "snippets": {
                     "my-element": "my-element"
          }
}
```

Which feels a little silly actually....

Or we could have a new setting `emmet.suggestions.additionalHtmlElements` where you can provide tags that should be considered in suggestions

**Comment by wernerm** [comment]
@ramya-rao-a Thanks. Having a setting available would be a nice way to address the issue.

**Comment by alexsasharegan** [comment]
It might be ideal for various contexts to customize emmet expansion by language setting to either utilize a whitelist of tag names or enable some kind of tag regex. In the vue context, custom tags almost contain a namespace prefix, so it could be something like `match: [/^el-*/, /^b-*/]`.

**Comment by ramya-rao-a** [comment]
@alexsasharegan Can you try the latest Insiders? You can get it from https://code.visualstudio.com/insiders

There I have enabled emmet suggestions for tag completion when the tag contains a single `-` or `:` in between text. That should help

**Comment by alexsasharegan** [comment]
Whoa... fancy new insiders icon! I like it 😉 

So, it's sort of working. Basic tag names are functioning:
![image](https://user-images.githubusercontent.com/16269252/29679845-9e12f13e-88b7-11e7-9a1d-a7d78c30c019.png)

Here we have a more verbose component name that is failing to suggest tag completion:
![image](https://user-images.githubusercontent.com/16269252/29679812-865c5210-88b7-11e7-9615-d38000b782c1.png)

**Comment by ramya-rao-a** [comment]
@alexsasharegan added support for tags with multiple `-` in them with https://github.com/Microsoft/vscode-emmet-helper/commit/8517fe7d373a2455bf9411434c8afe073b55a22b

Tomorrow's Insiders will have the fix

**Comment by alexsasharegan** [comment]
I'll give it a whirl tomorrow. Thank you!

**Comment by ramya-rao-a** [comment]
@alexsasharegan The vetur extension will need to use the latest version(1.0.22) for the emmet helper though.

**Comment by HerringtonDarkholme** [comment]
Thank @ramya-rao-a for continuous support!

**Comment by lucaskatayama** [comment]
@yyx990803 Thanks!!! That solved my TAB problem with those last versions!

**Comment by onezhaoyn** [comment]
the css emmet expansion in *.vue file works perfectly!
But the user CSS snippets for emmet in *.vue file not working ( user HTML snippets works fine!)
Could you please have a look?

i define a css snippet:
 ![image1](https://tva1.sinaimg.cn/large/0082zybpgy1gc6p5gxokdj307u02r0sn.jpg)

it works fine in *.styl file:
 ![image1](https://tva1.sinaimg.cn/large/0082zybpgy1gc6p5njcmsj30fh03xdfv.jpg)

but the user snippets now shown in *.vue file:
 ![image1](https://tva1.sinaimg.cn/large/0082zybpgy1gc6p5rnubij308m03fdft.jpg)

**Comment by mreduar** [comment]
> @alexsasharegan Can you try the latest Insiders? You can get it from https://code.visualstudio.com/insiders
> 
> There I have enabled emmet suggestions for tag completion when the tag contains a single `-` or `:` in between text. That should help

Greetings! I know this is an old topic, but I would like to know if there is a way that this behavior can be used for components that have neither `-` nor `:` Since Vue in its standards recommends the use of `PascalCase` for Single-File Components (SFCs) it would be great to be able to expand the custom elements.

> In SFCs, it's recommended to use PascalCase tag names for child components to differentiate from native HTML elements. Although native HTML tag names are case-insensitive, Vue SFC is a compiled format so we are able to use case-sensitive tag names in it. We are also able to use /> to close a tag.

More info [here](https://vuejs.org/guide/essentials/component-basics.html#using-a-component)
