### ISSUE TITLE
modelValue required prop warning despite usage of v-model

### ISSUE THREAD

**Issue by Akryum** [vuejs/vetur#2647]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform:  Linux
- Vetur version: 0.32.0
- VS Code version: 1.52.1

## Problem

The `modelValue` prop is marked as `required` in my `BaseInput` component. Despite using the `v-model` directive, Vetur displays an error that `modelValue` is required and isn't used:

![image](https://user-images.githubusercontent.com/2798204/105730339-889c2180-5f2e-11eb-9f4e-e3aa248c80ae.png)

## Reproducible Case

TODO

**Comment by yoyo930021** [comment]
Do your `BaseInput` component have `model` property?

**Comment by Blackfaded** [comment]
I am facing the same issue

**Comment by muodov** [comment]
@yoyo930021 

This is still a problem when a component defines both "value" and "modelValue" props. If I read the code correctly, the problem is coming from this line: https://github.com/vuejs/vetur/blame/78171ae446a71982708556b3950f08cc4dd0bd01/server/src/modes/script/componentInfo.ts#L342

I would make a PR, but don't have much time atm, hopefully someone can pick it up

**Comment by mariomadrigall205** [comment]
Algúnos años después, pero por si alguién tiene el problema. Esto se soluciona simplemente añadiendo el v-model="" de primer propiedad en la etiqueta que se este trabajando.

Saludos!
