### ISSUE TITLE
Support VSCode new bracket pair colorization feature

### ISSUE THREAD

**Issue by abc1236762** [vuejs/vetur#3141]
- [x] I have searched through existing issues

## Feature Request

According to https://github.com/microsoft/vscode/issues/132175#issuecomment-913205870, please add `colorizedBracketPairs` into language config json to make bracket pair colorization feature in VSCode more perfect to vue file, right now it will have wrong pairing between `<` and `>`

**Comment by HardKullez** [comment]
Would be also nice to have {{}} from Vue templates to be added as bracket pairs by default, something similar to https://github.com/microsoft/vscode/issues/132240#issuecomment-913380862

**Comment by lorand-horvath** [comment]
Added bracket pair colorization support in PR #3145

**Comment by fz6m** [comment]
Hope to merge soon. The development experience is pretty bad right now

<img src='https://user-images.githubusercontent.com/59400654/134161084-83e73eb5-da78-4d75-80a3-ff90738cccf0.png' width='20%' />

**Comment by lorand-horvath** [comment]
@fz6m It looks like the angle brackets have been removed from automatic colorization in VSCode, please see issue https://github.com/microsoft/vscode/issues/132476 and the fix for it https://github.com/microsoft/vscode/commit/152413e0a8d222cc88c3394cc27cf1b92944a7b8 which is supposed to arrive in the September version of VSCode 1.61

So I guess my PR #3145 will then be unnecessary.
