### ISSUE TITLE
Emmet support broken, "emmet.useNewEmmet" setting not recognised

### ISSUE THREAD

**Issue by wernerm** [vuejs/vetur#383]
- [x] I searched through existing issues.
- [x] I have looked through docs at https://vuejs.github.io/vetur/

## Info

- Platform: Linux
- Vetur version: 0.9.3
- VSCode version: 1.15.0

## Problem

1. No emmet support inside `template` element, despite having "emmet.useNewEmmet" set to false in settings (according to vetur docs). Settings done according to [docs](https://vuejs.github.io/vetur/emmet.html).
2. VSCode flags "emmet.useNewEmmet" setting as unavailable.

## Reproducible Case

1. Set up [recommended emmet settings](https://vuejs.github.io/vetur/emmet.html) in User Settings.
2. Try to invoke emmet inside `template` element of .vue file.

**Comment by zhuqingguang** [comment]
i have the same problem...have you resolve it?

**Comment by HerringtonDarkholme** [comment]
https://github.com/vuejs/vetur/issues/232

**Comment by Jetsly** [comment]
why closed?

**Comment by chulinyin** [comment]
I have the same problem after updated the VSCode, here is my info
- Platform: macOS
- Vetur version: 0.9.3
- VSCode version: 1.15.0

**Comment by Jetsly** [comment]
@chulinyin  you must set bind a `Tab` key to the  `editor.emmet.action.expandAbbreviation` command or use Emmet: Expand Abbreviation from the Command Palette.
https://code.visualstudio.com/updates/v1_15#_emmet-20

**Comment by chulinyin** [comment]
@Jetsly  thanks a lot for your information, I have just fixed it up by use `emmet.includeLanguages` instead of `emmet.syntaxProfiles`. Here is the doc: [emmet-suggestions-in-other-file-types](https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0#_emmet-suggestions-in-other-file-types) and [emmet-configuration](https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0#_emmet-configuration)

 Here is the screenshoot
![image](https://user-images.githubusercontent.com/16412234/29258536-01e79aac-80ed-11e7-8845-6d74af0a1f32.png)

![image](https://user-images.githubusercontent.com/16412234/29258489-afc79178-80ec-11e7-8fa4-55312103c356.png)

**Comment by HerringtonDarkholme** [comment]
We already have #232 to track issue with new emmet.

Please do search through existing issues before creating new issue, rather than click that tick.

**Comment by Jetsly** [comment]
![image](https://user-images.githubusercontent.com/6357863/29259072-ca70cd96-80f1-11e7-9efc-d590c10d141f.png)

**Comment by wernerm** [comment]
Thanks for the information, I can confirm that the suggested configuration works:
```
"emmet.includeLanguages": {
    "vue": "html",
    "vue-html": "html"
  }
```
I have suggested in #232 that the current documentation be updated to provide the new information.
