### ISSUE TITLE
Can not format html. js-beautify-html: html (deprecated and turned off by default)

### ISSUE THREAD

**Issue by yoyo837** [vuejs/vetur#484]
- [x] I have searched through existing issues
- [x] I have read through docs at https://vuejs.github.io/vetur/
- [x] I have read FAQ: https://github.com/vuejs/vetur/wiki/FAQ

## Info

- Platform: Win
- Vetur version: latest
- VSCode version: 1.17.2 64bit

## Problem
Can not format html (.vue template)

>js-beautify-html: html (deprecated and turned off by default)

In the absence of alternatives in the case of the default disabled js-beautify-html is reasonable? I can only open it, otherwise html can not be formatted.

**Comment by blocka** [comment]
You can reenable it if you want

**Comment by HerringtonDarkholme** [comment]
Please see our changelog.

https://github.com/vuejs/vetur/blob/master/CHANGELOG.md#vetur-formatting-changes

I would suggest vote by emoji on prettier's issue. We prefer prettier over js-beautify.

**Comment by octref** [comment]
You can always enable it. I have way too many people complaining about the html formatting, and our js-beautify issues just stay idle for months and maintainers are waiting for PRs instead of fixing them:

https://github.com/beautify-web/js-beautify/issues/1185
https://github.com/beautify-web/js-beautify/issues/1186
