### ISSUE TITLE
please use vscode's html formating tools to replace js-beautify for template formatting

### ISSUE THREAD

**Issue by transtone** [vuejs/vetur#524]
js-beautify is buggy, Could you please use vscode's inside html extension as default template formatting tools?

https://github.com/Microsoft/vscode/blob/master/extensions/html/server/src/modes/formatting.ts

**Comment by HerringtonDarkholme** [comment]
Sadly, it just uses js-beautify underhood :/ 

https://github.com/Microsoft/vscode-html-languageservice/blob/master/src/services/htmlFormatter.ts#L9

**Comment by transtone** [comment]
but vscode not have this bug:
https://github.com/vuejs/vetur/issues/488

so, what happend?

**Comment by HerringtonDarkholme** [comment]
Please use webstorm.

**Comment by Meesayen** [comment]
> Please use webstorm.

wow, that really fixed the issues, thanks!

**Comment by octref** [comment]
@Meesayen 
#488 is an upstream bug of js-beautify. js-beautify is disabled by default in Vetur because the upstream issues never get resolved. We have the following in [doc](https://vuejs.github.io/vetur/formatting.html):

> js-beautify has many long-standing bugs that never get fixed. Use at your own risk.

In this particular case we were able to work around this bug, but in principle we don't fix js-beautify bugs any more. I'm working on an alternative formatter.
