### ISSUE TITLE
attribute `lang="ts"` breaks IntelliSense 

### ISSUE THREAD

**Issue by lmk123** [vuejs/vetur#564]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.11.3
- VS Code version: 1.18.1

Vanilla VSCode, with only Vetur enabled.

## Problem

It's exactly the same as #111, but it's in the lastest VS Code and Vetur.

## Reproducible Case

Open [Counter.vue](https://github.com/octref/veturpack/blob/master/client/components/Counter.vue) in [Veturpack](https://github.com/octref/veturpack).

If no lang is added, completion works:

![image](https://user-images.githubusercontent.com/5035625/33360052-ea91050e-d50c-11e7-9db9-4be805884eb6.png)

However, `lang="ts"` breaks this.

![image](https://user-images.githubusercontent.com/5035625/33360059-f8ef3a6c-d50c-11e7-8130-3234a0a5f748.png)

**Comment by HerringtonDarkholme** [comment]
https://vuejs.org/v2/guide/typescript.html#Basic-Usage

> To let TypeScript properly infer types inside Vue component options, you need to define components with Vue.component or Vue.extend

**Comment by HerringtonDarkholme** [comment]
For the curious:

We used to wrap TypeScript component export in `Vue.extend` call in order to get semantic completion. However, it turned to be problematic for other tools like ts-loader where no (enough) special operation is done for Vue SFC.  For example, accessing properties on `this` will trigger errors in ts-loader if `noImplicitThis` is set, but Vetur requires that flag to provide completion.

So we remove auto wrapping in TS and users have to provide wrapping themselves.

**Comment by mmitchellgarcia** [comment]
@HerringtonDarkholme Is the issue with intellisense missing in `Vue.extend` resolvable? If not, how do we wrap the component ourselves? Is it recommended we migrate to class-style components? Thanks!

**Comment by HerringtonDarkholme** [comment]
@mmitchellgarcia  You can always wrap component option in `Vue.extend` manually. `noImplicitThis` will type check your option object.
