### ISSUE TITLE
Unquoted attribute values with dots in them

### ISSUE THREAD

**Issue by rightaway** [vuejs/vetur#668]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux
- Vetur version: latest
- VS Code version: latest

## Problem

When you have an attribute value without quotes, it works fine unless the value has a dot in it. For example `key=value` is highlighted correctly, with key and value being different colors. But `key=value.one.two` isn't, where the whole `value.one.two` gets formatted the same color as `key`.

If the attribute value is quoted then you get correct highlighting, where `value`, `one`, and `two` are different colors. Since unquoted attributes are allowed in Vue I think the highlighting should work the same whether there's quotes or not even when the value has dots in it.

**Comment by HerringtonDarkholme** [comment]
We recently received **a lot of** suggestions on unquoted attributes.

May I ask the benefit of unquoted attributes? Other than 1 fewer key stroke?

**Comment by HerringtonDarkholme** [comment]
#670  #666 #639  #668

**Comment by rightaway** [comment]
For me the main benefit is mainly about less visual clutter on the screen. The less characters that are there, the cleaner and clearer things look. Also I like the idea that if something isn't necessary and doesn't affect readability, then it shouldn't be there (in my opinion unquoted attributes with appropriate syntax highlighting don't decrease readability but increase it).

**Comment by HerringtonDarkholme** [comment]
You really should use Jade. HTML is full of clutter by design.

**Comment by rightaway** [comment]
I don't see the benefit in disallowing a code style that isn't disallowed by Vue but it's your project so of course up to you.

https://github.com/vuejs/vetur/issues/639 had the same discussion but you kindly fixed the unquoted attribute highlighting issue even though you disagree with unquoted attributes, I'm just suggesting that it works for attributes with dots in them too.

After all why should unquoted attributes with dots and without dots be treated differently? If you fully disagree with unquoted attributes then I would actually think it's better to revert the fix in https://github.com/vuejs/vetur/issues/639 and don't support unquoted attributes at all rather than handling them differently if there's a dot in the middle, because inconsistent handling is a bug in my opinion.

**Comment by HerringtonDarkholme** [comment]
Because I don't want to spend my time on bike shedding. We already have tons of configuration for users to configure and multiple styles to support. There should be one way to do one thing properly, I bet Danish will agree me.

For quoteless value it should be fixed and I cannot reproduce what you said.

If you do want to fully support quoteless value, say JavaScript expression highlight. You really should spend some time in open source project.

**Comment by octref** [comment]
@HerringtonDarkholme Let's not be too harsh...

@rightaway The thing is after syntax highlighting, people can also ask for IntelliSense, error checking etc for the interpolations. We don't have support for those yet, even in quoted attributes. Implementing them is hard and takes time. So instead of adding very limited support for a new feature not yet adopted by the community and making the bigger problem of "having good JS support in interpolations" many times harder, I would like to focus more on having richer support for interpolations.

And as @HerringtonDarkholme said. If you are so much into quoteless values, use jade/pug, which we do plan to build more support for.
