### ISSUE TITLE
vue file has  two style(lang="stylus")  format wrong

### ISSUE THREAD

**Issue by sheepdragon** [vuejs/vetur#736]
## Info

- Platform: Win
- Vetur version:0.11.7
- VS Code version:1.21.1

## Problem

before formatting：
![1](https://user-images.githubusercontent.com/4659052/37699068-adca0ab4-2d20-11e8-9ecc-17d8039ab33a.png)

after formatting:
![2](https://user-images.githubusercontent.com/4659052/37699108-deeab878-2d20-11e8-9565-3c57f4f042f9.png)

The two style became the same

**Comment by HerringtonDarkholme** [comment]
We currently don't support multiple language blocks.

Please see https://github.com/vuejs/vetur/issues/430

**Comment by gooqiao** [comment]
Hopefully it can be supported because it does not violate the vue style guide, and it does have its actual effect.
for example:
I have a page with a dialog on the page. I wrote the dialog for this page as a component. However, there is something on the dialog that is the same as on the page. Assuming I use the style tag with scoped, I will have to write it both in the dialog component and in the page component.

**Comment by octref** [comment]
Related to #532 too.

**Comment by KennyWho** [comment]
same as [https://github.com/vuejs/vetur/issues/499]

**Comment by octref** [comment]
Tracked in #499.

**Comment by octref** [comment]
Tracked in #499.
